# Can be run successfully

# Generated by Selenium IDE

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome('D:\GitRoot\pros\Selenium\chromedriver\chromedriver_win32_104\chromedriver.exe')
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t1(self):
    self.driver.get("https://www.cpbl.com.tw/")
    self.driver.set_window_size(1346, 708)
    self.driver.find_element(By.LINK_TEXT, "球隊戰績").click()
    self.driver.find_element(By.LINK_TEXT, "本季球隊戰績").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) .sticky_wrap a").click()
    self.driver.find_element(By.LINK_TEXT, "球員異動").click()
    self.driver.find_element(By.LINK_TEXT, "團隊成績").click()
    self.driver.find_element(By.LINK_TEXT, "陳傑憲").click()
  
