RUN("notepad.exe")
WinWaitActive("未命名 - 記事本")
Send("Hello Autoit'{Enter}")
WinClose("*未命名 - 記事本")
WinWaitActive("記事本","不要儲存(&N)")
ControlClick("記事本","儲存(&N)","[CLASS:Button; INSTANCE:1]")
WinWaitActive("另存新檔")
Send("Autoit-1")
ControlClick("另存新檔","存檔(&S)","[CLASS:Button; INSTANCE:2]")
WinWaitActive("確認另存新檔")
ControlClick("確認另存新檔","是(&Y)","[CLASS:Button; INSTANCE:1]")
#Send("!n")