# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_untitled(self):
    self.driver.get("https://www.thsrc.com.tw/")
    self.driver.set_window_size(1346, 708)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, "#aIRS img").click()
    self.vars["win9560"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win9560"])
    self.driver.find_element(By.NAME, "selectStartStation").click()
    dropdown = self.driver.find_element(By.NAME, "selectStartStation")
    dropdown.find_element(By.XPATH, "//option[. = '台北']").click()
    self.driver.find_element(By.NAME, "selectDestinationStation").click()
    dropdown = self.driver.find_element(By.NAME, "selectDestinationStation")
    dropdown.find_element(By.XPATH, "//option[. = '台中']").click()
    self.driver.find_element(By.ID, "toTimeInputField").click()
    self.driver.find_element(By.ID, "toTimeInputField").send_keys("2022/05/30")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.NAME, "toTimeTable").click()
    dropdown = self.driver.find_element(By.NAME, "toTimeTable")
    dropdown.find_element(By.XPATH, "//option[. = '12:30']").click()
    self.driver.find_element(By.NAME, "ticketPanel:rows:0:ticketAmount").click()
    dropdown = self.driver.find_element(By.NAME, "ticketPanel:rows:0:ticketAmount")
    dropdown.find_element(By.XPATH, "//option[. = '1']").click()
    self.driver.find_element(By.ID, "securityCode").click()
    self.driver.find_element(By.ID, "securityCode").send_keys("7HM5")
    self.driver.find_element(By.ID, "SubmitButton").click()
    self.driver.execute_script("window.scrollTo(0,200)")
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(7) input").click()
    self.driver.find_element(By.NAME, "SubmitButton").click()
    self.driver.find_element(By.ID, "idNumber").click()
    self.driver.find_element(By.ID, "idNumber").send_keys("A123456789")
    self.driver.find_element(By.ID, "mobilePhone").click()
    self.driver.find_element(By.ID, "mobilePhone").send_keys("0912345678")
    self.driver.find_element(By.ID, "name2622").click()
    self.driver.find_element(By.ID, "name2622").send_keys("p12345@gmail.com")
  
